GET http://localhost:3333/species/species-all

###

GET http://localhost:3333/species/species-all-catalog

###

POST  http://localhost:3333/species/specie-create
Content-Type: application/json

{
  "nomePopular": "Quero-Quero",
  "nomeCientifico": "Vanellus chilensis",
  "reino": "Animalia",
  "filo": "Chordata",
  "classe": "Aves",
  "ordem": "Charadriiformes",
  "familia": "Charadriidae",
  "genero": "Vanellus",
  "especie": "chilensis",
    "descricao": "O quero-quero é uma ave da família dos caradriídeos, também conhecido como abibe-do-sul, abibe, agachona, apereá ou terecã. O nome científico é Vanellus chilensis. O quero-quero é uma ave típica da América do Sul, sendo encontrado desde a Argentina e leste da Bolívia até a margem direita do rio Amazonas, no Brasil."
}



###

POST http://localhost:3333/admins/admins-login
Content-Type: application/json

{
    "email": "gabriel@gmail.com",
    "senha": "teste@"
}