GET http://localhost:3333/species/specie/6c1b16cd-8ab3-44c4-9e7c-6de842d4d518

###

GET http://localhost:3333/species/specie-contributions/6c1b16cd-8ab3-44c4-9e7c-6de842d4d518

###

GET http://localhost:3333/species/specie-locations/6c1b16cd-8ab3-44c4-9e7c-6de842d4d518

###
GET http://localhost:3333/species/species-all-catalog

###


GET http://localhost:3333/species/species-all-crud

###
POST http://localhost:3333/species/specie-create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJlbWFpbCI6ImdhYnJpZWxAZ21haWwuY29tIiwiaWF0IjoxNzI3MzA1OTE2LCJleHAiOjE3MjczMDk1MTZ9.SroNTSO6H4P1WpBdsNhQo2eidZWn-TNX5D16T6IZOOc
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dados"

{
  "nomePopular": "Preá",
  "nomeCientifico": "Galea spixii",
  "reino": "Animalia",
  "filo": "Chordata",
  "classe": "Mammalia",
  "ordem": "Rodentia",
  "familia": "Caviidae",
  "genero": "Galea",
  "especie": "spixii",
  "descricao": "O preá, cientificamente chamado de Galea spixii, é um roedor nativo da América do Sul, comumente encontrado no Brasil, Argentina e Paraguai. Ele habita áreas de vegetação densa, como savanas e florestas tropicais. O preá é herbívoro e se alimenta de gramíneas e folhas. É um animal pequeno e ágil, com pelagem curta e de cor variando entre o marrom e o cinza. Ele é frequentemente comparado à capivara, embora seja menor."
}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="imagem"; filename="queroquero.jpg"
Content-Type: image/jpeg

# [conteúdo binário da imagem aqui]
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

POST http://localhost:3333/admins/admins-login
Content-Type: application/json

{
    "email": "gabriel@gmail.com",
    "senha": "teste@"
}